<?php
$myArray = 
array ( 1 => array ( 'A' => 'Region', 'B' => 'Reporting Month', 'C' => 'Date Leads Sent', 'D' => 'Vendor Name', 'E' => 'Vendor ID', 'F' => 'Encrypted File Path', 'G' => 'Decrypted File Path', 'H' => 'Upload Number', 'I' => 'Filename', 'J' => 'Upload Timestamp', 'K' => 'Leads Loaded', 'L' => 'Leads Rejected', 'M' => 'Lead List File Name and/or FTP Site Address', 'N' => 'OUTPUT ID#', 'O' => 'FILE ID#', 'P' => 'Segment by', 'Q' => 'LIST/OP SEGMENT #', 'R' => 'WTN COUNT ', 'S' => 'BTN COUNT', 'T' => 'LOC COUNT', 'U' => 'COMPANY COUNT', 'V' => 'Date In Lead History', 'W' => 'Lead HistoryID', 'X' => 'REPORT BTN COUNTS AS LEADS RECEIVED (NLA=No Leads Available)', 'Y' => 'Campaign Type', 'Z' => 'Campaign Program', 'AA' => 'Campaign Name', 'AB' => 'FILE LAYOUT', 'AC' => 'Leads sent by ', 'AD' => 'Misc. Notes', ), 2 => array ( 'A' => 'NE', 'B' => 'OCT', 'C' => '4-Oct', 'D' => 'BVN', 'E' => 'BVN', 'F' => NULL, 'G' => NULL, 'H' => NULL, 'I' => NULL, 'J' => NULL, 'K' => NULL, 'L' => NULL, 'M' => 'Il_MD ACG List v4.csv', 'N' => NULL, 'O' => NULL, 'P' => 'stateOrProvince', 'Q' => 'MD', 'R' => NULL, 'S' => NULL, 'T' => NULL, 'U' => NULL, 'V' => NULL, 'W' => NULL, 'X' => NULL, 'Y' => 'OB', 'Z' => 'PEN', 'AA' => 'New campaign', 'AB' => 'BVN', 'AC' => NULL, 'AD' => NULL, ), 3 => array ( 'A' => 'MW', 'B' => 'OCT', 'C' => '4-Oct', 'D' => 'BVN', 'E' => 'BVN', 'F' => NULL, 'G' => NULL, 'H' => NULL, 'I' => NULL, 'J' => NULL, 'K' => NULL, 'L' => NULL, 'M' => 'Il_MD ACG List v4.csv', 'N' => NULL, 'O' => NULL, 'P' => 'stateOrProvince', 'Q' => 'IL', 'R' => NULL, 'S' => NULL, 'T' => NULL, 'U' => NULL, 'V' => NULL, 'W' => NULL, 'X' => NULL, 'Y' => 'OB', 'Z' => 'PEN', 'AA' => 'New campaign', 'AB' => 'BVN', 'AC' => NULL, 'AD' => NULL, ), );
/*[
	1 =>
	[
	  'A' =>'Region',
      'B' =>'Reporting Month',
      'C' =>'Date Leads Sent', 
      'D' =>'Vendor Name', 
      'E' =>'Vendor ID', 
      'F' =>'Encrypted File Path',
      'G' =>'Decrypted File Path',
      'H' =>'Upload Number',
      'I' =>'Filename', 
      'J' =>'Upload Timestamp',
      'K' =>'Leads Loaded',
      'L' =>'Leads Rejected', 
      'M' =>'Lead List File Name and/or FTP Site Address',
      'N' =>'OUTPUT ID#', 
      'O' =>'FILE ID#', 
      'P' =>'Segment by', 
      'Q' =>'LIST/OP SEGMENT #',
      'R' =>'WTN COUNT ', 
      'S' =>'BTN COUNT', 
      'T' =>'LOC COUNT', 
      'U' =>'COMPANY COUNT',
      'V' =>'Date In Lead History',
      'W' =>'Lead HistoryID', 
      'X' =>'REPORT BTN   COUNTS AS LEADS RECEIVED (NLA=No Leads Available)',
      'Y' =>'Campaign Type',
      'Z' =>'Campaign Program',
      'AA' =>'Campaign Name',
      'AB' =>'FILE LAYOUT', 
      'AC' =>'Leads sent by  ', 
      'AD' =>'Misc. Notes', 
      'AE' => null,
      'AF' => null,
      'AG' => null,
      'AH' => null,
      'AI' => null,
      'AJ' => null
    ],
    2 => 
    [
      'A' =>'SE', 
      'B' =>'SEP', 
      'C' =>'29-Aug', 
      'D' =>'ACG (In Language)',
      'E' =>'ACL_SE',
      'F' =>'J:\Lists\Encrypted\ACL\SE\RTN\RNWL TARGET CITIES SEP\157407_SepACGL_SE_AT&T_Proprietary_(Restricted)_authorized_individuals_Only.txt.gpg',
      'G' =>'J:\Lists\Decrypted\ACL\SE\RTN\RNWL TARGET CITIES SEP\157407_SepACGL_SE_AT&T_Proprietary_(Restricted)_authorized_individuals_Only.txt',
      'H' => null,
      'I' => null,
      'J' => null,
      'K' => null,
      'L' => null,
      'M' =>'test157407_SepACGL_SE_AT&T_Proprietary_(Restricted)_authorized_individuals_Only.txt',
      'N' => null,
      'O' => null,
      'P' =>'flag2', 
      'Q' => 2,
      'R' =>' 134', 
      'S' =>' 60', 
      'T' =>' 60', 
      'U' =>' 59', 
      'V' =>'09-12-12', 
      'W' =>' 460', 
      'X' =>' 60', 
      'Y' =>'OB', 
      'Z' =>'RTN' ,
      'AA' =>'RNWL TARGET CITIES SEP',
      'AB' =>'RETENTION', 
      'AC' =>'PHAM, PHILIP B', 
      'AD' =>'RPT ALL LEADS RCVD ON 9/4; DO NOT DIAL UNTIL 9/4', 
      'AE' => null,
      'AF' => null,
      'AG' => null,
      'AH' => null,
      'AI' => null,
      'AJ' => null
    ],
  	3 => 
    [
      'A' =>'SE', 
      'B' =>'SEP', 
      'C' =>'29-Aug', 
      'D' =>'ACG (In Language)',
      'E' =>'ACL_SE' ,
      'F' =>'J:\Lists\Encrypted\ACL\SE\RTN\RNWL TARGET CITIES SEP\157407_SepACGL_SE_AT&T_Proprietary_(Restricted)_authorized_individuals_Only.txt.gpg',
      'G' =>'J:\Lists\Decrypted\ACL\SE\RTN\RNWL TARGET CITIES SEP\157407_SepACGL_SE_AT&T_Proprietary_(Restricted)_authorized_individuals_Only.txt',
      'H' => null,
      'I' => null,
      'J' => null,
      'K' => null,
      'L' => null,
      'M' =>'test157407_SepACGL_SE_AT&T_Proprietary_(Restricted)_authorized_individuals_Only.txt',
      'N' => null,
      'O' => null,
      'P' =>'flag2', 
      'Q' => 3,
      'R' =>' 6', 
      'S' =>' 5', 
      'T' =>' 5', 
      'U' =>' 5', 
      'V' =>'09-12-12', 
      'W' =>' 461', 
      'X' =>' 5', 
      'Y' =>'OB', 
      'Z' =>'RTN', 
      'AA' =>'RNWL CTXOTH SEP', 
      'AB' =>'RETENTION', 
      'AC' =>'PHAM, PHILIP B', 
      'AD' =>'RPT ALL LEADS RCVD ON 9/4; DO NOT DIAL UNTIL 9/4', 
      'AE' => null,
      'AF' => null,
      'AG' => null,
      'AH' => null,
      'AI' => null,
      'AJ' => null
	]
]*/
//array ( 1 => array ( 'A' => 'Region', 'B' => 'Reporting Month', 'C' => 'Date Leads Sent', 'D' => 'Vendor Name', 'E' => 'Vendor ID', 'F' => 'Encrypted File Path', 'G' => 'Decrypted File Path', 'H' => 'Upload Number', 'I' => 'Filename', 'J' => 'Upload Timestamp', 'K' => 'Leads Loaded', 'L' => 'Leads Rejected', 'M' => 'Lead List File Name and/or FTP Site Address', 'N' => 'OUTPUT ID#', 'O' => 'FILE ID#', 'P' => 'Segment by', 'Q' => 'LIST/OP SEGMENT #', 'R' => 'WTN COUNT ', 'S' => 'BTN COUNT', 'T' => 'LOC COUNT', 'U' => 'COMPANY COUNT', 'V' => 'Date In Lead History', 'W' => 'Lead HistoryID', 'X' => 'REPORT BTN COUNTS AS LEADS RECEIVED (NLA=No Leads Available)', 'Y' => 'Campaign Type', 'Z' => 'Campaign Program', 'AA' => 'Campaign Name', 'AB' => 'FILE LAYOUT', 'AC' => 'Leads sent by ', 'AD' => 'Misc. Notes', ), 2 => array ( 'A' => 'NE', 'B' => 'SEP', 'C' => '27-Sep', 'D' => 'HOP', 'E' => 'HOP', 'F' => NULL, 'G' => NULL, 'H' => NULL, 'I' => NULL, 'J' => NULL, 'K' => NULL, 'L' => NULL, 'M' => 'HOP_UI Commercial Leads_100511.txt', 'N' => NULL, 'O' => NULL, 'P' => 'NA', 'Q' => 'NA', 'R' => NULL, 'S' => NULL, 'T' => NULL, 'U' => NULL, 'V' => NULL, 'W' => NULL, 'X' => NULL, 'Y' => 'OB', 'Z' => 'PEN', 'AA' => 'New campaign', 'AB' => 'HOP', 'AC' => NULL, 'AD' => NULL, ), );

?>